#
# Makefile for Phoenix-RTOS 3 device drivers
#
# iMX6ULL tool set
#
# Copyright 2019 Phoenix Systems
#

CFLAGS += -DTARGET_IMX6ULL

include psh/Makefile
include pinit/Makefile
#include psd/imx6ull/Makefile
