#
# Makefile for Phoenix-RTOS meterfs-migrate
#
# Copyright 2021 Phoenix Systems
#

NAME := meterfs-migrate
LOCAL_PATH = $(call my-dir)
SRCS := $(wildcard $(LOCAL_PATH)*.c)
LOCAL_INSTALL_PATH := /bin

include $(binary.mk)
