#
# Makefile for Phoenix-RTOS 3 device drivers
#
# iMX6ULL tool set
#
# Copyright 2019 Phoenix Systems
#

DEFAULT_COMPONENTS := psh psd psd-old nandtool nandpart metacheck bench_common rh_msg_latency rh_msg_latency_send rh_preemption
