#
# Makefile for Phoenix-RTOS psd (Phoenix Serial Downloader)
#
# Copyright 2018, 2019 Phoenix Systems
#

$(PREFIX_PROG)psd: $(PREFIX_O)psd/psd.o $(PREFIX_O)psd/hid.o
	$(LINK)

all: $(PREFIX_PROG_STRIPPED)psd
