#
# Makefile for Phoenix-RTOS spitool
#
# Copyright 2022 Phoenix Systems
#

NAME := spitool
LOCAL_PATH = $(call my-dir)
SRCS := $(wildcard $(LOCAL_PATH)*.c)
LOCAL_INSTALL_PATH := /bin
LIBS := libspi-msg

include $(binary.mk)
